In [1]:
import numpy as np
import cv2
import math
bgr = cv2.imread("parrot.jpg",1)
cv2.imshow('parrot ',bgr)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [2]:
bgr.shape

(768, 1024, 3)

# Conversion of BGR default to it's constituent colors.

In [3]:
# cv2.imshow('parrot in rgb',bgr)    --------> not needed at this moment.
cv2.waitKey(0)
cv2.destroyAllWindows()
b, g, r = cv2.split(bgr) 

In [4]:
# The RGB color models which consistes of 3 tupples are split in 3 components of Red , Green , Blue respectively . 

In [5]:
red = np.array(r)
print(red)

[[ 99 100 102 ...  78  84  87]
 [101 102 103 ...  77  83  86]
 [103 104 105 ...  76  81  83]
 ...
 [113 112 108 ...  41  41  40]
 [113 112 109 ...  42  40  39]
 [114 112 110 ...  42  41  40]]


In [6]:
red.shape

(768, 1024)

In [7]:
green = np.array(g)
print(green)

[[137 138 140 ... 131 137 140]
 [139 140 141 ... 130 136 139]
 [141 142 143 ... 129 134 136]
 ...
 [135 134 132 ...  75  73  72]
 [137 136 133 ...  76  74  73]
 [138 136 134 ...  76  75  74]]


In [8]:
blue = np.array(b)
print(blue)

[[ 98  99 103 ...  77  83  86]
 [100 101 104 ...  76  82  85]
 [102 103 104 ...  75  80  82]
 ...
 [ 52  51  48 ...  38  36  35]
 [ 51  50  47 ...  39  37  36]
 [ 52  50  48 ...  39  38  37]]


**Here you can see the seperate channels of the image of r - g - b channels.**

In [9]:
cv2.imshow('color channels red',red)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [10]:
cv2.imshow('color channels green',green)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
cv2.imshow('color channels blue',blue)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Conversion of RGB to CMY  form 

**We would be trying it with 2 methods**
 1. Using pre-build python function to perform the operations
 2. Using formulae to calculate it .

Since we  know that Relation that  [C M Y] = [1 1 1] - [ R G B]  for each and every individual tupple value so we will be doing the same in the below few lines .

In [12]:
# creating a 2d array with all the component to be one 1 .

oneO = np.ones([768, 1024])
print(oneO)

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [13]:
oneO=255*oneO
print()
print(oneO)


[[255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 ...
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]
 [255. 255. 255. ... 255. 255. 255.]]


**cyan**

In [14]:
cyan = oneO-red
print(cyan)

[[156. 155. 153. ... 177. 171. 168.]
 [154. 153. 152. ... 178. 172. 169.]
 [152. 151. 150. ... 179. 174. 172.]
 ...
 [142. 143. 147. ... 214. 214. 215.]
 [142. 143. 146. ... 213. 215. 216.]
 [141. 143. 145. ... 213. 214. 215.]]


In [15]:
cv2.imshow('Conversion to CMY model ',cyan)

**magenta**

In [16]:
magenta = oneO-green
print(magenta)

[[118. 117. 115. ... 124. 118. 115.]
 [116. 115. 114. ... 125. 119. 116.]
 [114. 113. 112. ... 126. 121. 119.]
 ...
 [120. 121. 123. ... 180. 182. 183.]
 [118. 119. 122. ... 179. 181. 182.]
 [117. 119. 121. ... 179. 180. 181.]]


In [17]:
cv2.imshow('Conversion to CMY model ',magenta)

**Yellow**

In [18]:
yellow = oneO-blue
print(yellow)

[[157. 156. 152. ... 178. 172. 169.]
 [155. 154. 151. ... 179. 173. 170.]
 [153. 152. 151. ... 180. 175. 173.]
 ...
 [203. 204. 207. ... 217. 219. 220.]
 [204. 205. 208. ... 216. 218. 219.]
 [203. 205. 207. ... 216. 217. 218.]]


**Merging the cmy color channels in one to form a image.** 

In [19]:
cmy_img = cv2.merge([cyan,magenta,yellow])

In [20]:
cv2.imshow('Conversion to CMY model ',cmy_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Conversion of RGB to HSI

In [21]:
# lets convert the red, green , blue in normalization form 
red= red/255

In [22]:
blue= blue/255

In [23]:
green = green/255

![](HFormula.png)

In [24]:
theeta =   np.arccos((((r-g)+(r-b))/ (2*(np.sqrt(((r-g)*(r-g))+((r-b)*(g-b)))))))

C:\Users\Satyam Dubey\AppData\Local\Temp\ipykernel_1876\4036046993.py:1: RuntimeWarning: divide by zero encountered in true_divide
  theeta =   np.arccos((((r-g)+(r-b))/ (2*(np.sqrt(((r-g)*(r-g))+((r-b)*(g-b)))))))
C:\Users\Satyam Dubey\AppData\Local\Temp\ipykernel_1876\4036046993.py:1: RuntimeWarning: invalid value encountered in true_divide
  theeta =   np.arccos((((r-g)+(r-b))/ (2*(np.sqrt(((r-g)*(r-g))+((r-b)*(g-b)))))))
C:\Users\Satyam Dubey\AppData\Local\Temp\ipykernel_1876\4036046993.py:1: RuntimeWarning: invalid value encountered in arccos
  theeta =   np.arccos((((r-g)+(r-b))/ (2*(np.sqrt(((r-g)*(r-g))+((r-b)*(g-b)))))))


In [25]:
theeta

array([[nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       ...,
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan],
       [nan, nan, nan, ..., nan, nan, nan]], dtype=float16)

# Saturation 

In [26]:
# saturation

**----------------------------------------------------------------------------------------------------------------------------**

**Using Alternate method to convert rgb to hsi. **

In [27]:
HSI_img = cv2.cvtColor(bgr, cv2.COLOR_BGR2HSV)
cv2.imshow('horse hsi to rgb',HSI_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# HSI to RGB Conversion 
     ** 1st Direct method**
     ** 2nd Mushkil Method😥**
     

![](hsi2rgb.png)

In [28]:
# Direct method 
rgb_img = cv2.cvtColor(HSI_img, cv2.COLOR_HSV2BGR)
cv2.imshow('horse hsi to rgb',rgb_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

**2nd Method...**

In [29]:
# lets first split the h s i component into it's constituent components.

In [30]:
h, s, i = cv2.split(HSI_img) 

In [31]:
H = np.array(h)
S = np.array(s)
I = np.array(i)

In [32]:
I

array([[137, 138, 140, ..., 131, 137, 140],
       [139, 140, 141, ..., 130, 136, 139],
       [141, 142, 143, ..., 129, 134, 136],
       ...,
       [135, 134, 132, ...,  75,  73,  72],
       [137, 136, 133, ...,  76,  74,  73],
       [138, 136, 134, ...,  76,  75,  74]], dtype=uint8)

In [33]:
rows, cols = (768, 1024)
bue = [[0 for i in range(cols)] for j in range(rows)]
rod = [[0 for i in range(cols)] for j in range(rows)]
gron = [[0 for i in range(cols)] for j in range(rows)]
RODE = np.array(rod)
GRON= np.array(gron)                                                
BUE = np.array(bue)
print()
for i in range(0,768):
    for j in range(0,1024):
        if H[i][j]>=0 and H[i][j]<120:
           BUE[i][j] = (I[i][j])*(255- S[i][j])
#            print(i," ",j)
#            print(RODE.shape)
           RODE[i][j] = (I[i][j])*(255+(((S[i][j])* (math.cos(H[i][j]))))/math. cos(60-(H[i][j])))  
#            print("hello {} {}",i,j)
#         elif H[i][j]<= 120 and H[i][j]<240:
#             H[i][j] = H[i][j] - 120
#             RODE = (I[i][j])*(255-(S[i][j]))
#             GRON = I[i][j] * (255+((S[i][j])*math.cos(H[i][j])))
            


In [34]:
BUE

array([[24934, 25254, 26040, ..., 19650, 21098, 21980],
       [25437, 25760, 26226, ..., 19370, 20944, 21684],
       [25944, 26270, 26455, ..., 19092, 20368, 20944],
       ...,
       [13230, 12998, 12276, ...,  9675,  9198,  8928],
       [13015, 12784, 11970, ...,  9956,  9398,  9198],
       [13248, 12784, 12194, ...,  9956,  9675,  9398]])